spring:
  profiles:
    active: @profileActive@
---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234561
    url: jdbc:mysql://47.98.202.133:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 47.98.202.133
    port: 6379
    password: 1234561
  main:
    allow-bean-definition-overriding: true
  mvc:
    view:
        suffix: .ftl
projectUrl:
  wechatMpAuthorize: http://sell.jeremy7.cn
  wechatOpenAuthorize: http://sell.jeremy7.cn
  sell: http://sell.jeremy7.cn
server:
  servlet:
    context-path: /sell

---
spring:
  profiles: pro
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234561
    url: jdbc:mysql://47.98.202.133:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 47.98.202.133
    port: 6379
    password: 1234561
  main:
    allow-bean-definition-overriding: true
  mvc:
    view:
      suffix: .ftl
projectUrl:
  wechatMpAuthorize: http://sell.jeremy7.cn
  wechatOpenAuthorize: http://sell.jeremy7.cn
  sell: http://sell.jeremy7.cn
---
#公共配置
weixin:
  #测试账号appid
  mpAppId: wxeb7a44cb0e923a00
  #微信支付appid
  #mpAppId: wxd898fcb01713c658
  #测试账号密钥
  mpSecretKey: 552d1e4ddf39b19a61e8bb419beca8d7
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: 098F6BCD4621D373CADE4E832627B4F6
  notifyUrl: http://selles.natapp1.cc/sell/pay/notify
  keyPath: /var/h5.p12
  templateId:
    orderStatus: 35353535



